name: root
channels:
- defaults
- conda-forge
dependencies:
- cxx-compiler
- mkl-service
- pymc3=3.8
- tqdm
- pandas
- seaborn
- jupyterlab
- pip
- numpy
- scipy
- nose
- cython
- pip:
  - cobra
  - git+https://github.com/pstjohn/emll
